version: '3.8'
services:
  heartbot:
    image: promisewrite:${TAG}
    container_name: heartbot
    ports:
      - "${PROMISEWRITE_PORT}:8080"
      - "1234:1234"
      - "3000:3000"
    restart: "always"
